const paragraphs = [
    "Hidup adalah sebuah film. Tuliskan akhir cerita yang Anda inginkan. Tetap percaya.",
    "Menyerah berarti menerima bahwa kamu lelah. Tetapi untuk beristirahat dan mencoba lagi adalah tanda sebuah tekad.",
    "Menjadi kuat bukan berarti kamu tidak pernah lelah. Itu hanya berarti kamu memiliki kekuatan untuk bangkit kembali setelah beristirahat.",
    "Bertahan hidup di dunia yang kejam ini adalah bisnis yang melelahkan, tetapi banyak penghargaan di akhir pertempuran.",
    "Jangan pernah lelah dengan mimpi, jika tidak terpenuhi. Ketakutan akan kegagalan seharusnya tidak menghalangimu dari jalan kepercayaan diri.",
    "Apa pun yang terjadi dalam hidupmu, kesusahan maupun kesenangan, syukuri saja dulu. Lalu, maknai hal positif apa yang dapat kamu ambil dari kejadian itu. Seburuk apa pun kejadian itu, pasti ada hal positif yang bisa diambil.",
    "Jangan lemah, hidup sedang mengajarimu bagaimana bertahan dengan baik. Ketika kamu jatuh, bangunlah untuk memegang impianmu kembali. Ketika kamu ragu, kuatkan doamu karena saat itu hanya rasa percaya kepada Tuhan yang mampu menghilangkan ragumu terhadap apa yang kamu ragukan itu.",
    "Hati yang selalu bersyukur akan menemukan berbagai kesempatan, maka tunjukkan dan milikilah rasa bersyukur itu.",
    "Selama kita memiliki tujuan besar untuk dicapai, tidak pantas patah semangat di tengah jalan. Ingat! Tidak ada kesuksesan yang bisa diraih tanpa melalui hambatan.",
    "Kebahagiaan bukanlah sesuatu yang sudah tercipta, namun kebahagiaan itu muncul dari berbagai tindakan dan pemikiran yang dimiliki oleh seseorang.",
    "Masalah yang kamu hadapi bukan untuk menjatuhkanmu, tetapi agar kamu bisa berpikir lebih dewasa dari hari ini, kemarin dan sebelumnya.",
    "Anda belajar lebih banyak dari kegagalan daripada dari kesuksesan. Jangan biarkan kegagalan menghentikan Anda. Kegagalan membangun karakter.",
    "Hanya ada dua pilihan untuk memenangkan kehidupan, yaitu keberanian atau keikhlasan. Jika tidak berani, ikhlaslah menerimanya. Jika tidak ikhlas, maka beranilah untuk mengubahnya.",
    "Jadilah seperti lilin, yang tidak pernah menyesal saat nyala api membakarmu. Jadilah seperti air yang mengalir sabar. Jangan pernah takut memulai hal baru.",
    "Daun yang jatuh tak pernah membenci angin. Dia membiarkan dirinya jatuh begitu saja. Tak melawan, mengikhlaskan semua.",
    "Hanya karena seseorang itu sabar tingkat langit, maka bukan berarti dia lantas bisa disakiti, diinjak begitu saja. Hanya karena seseorang kuat, strong, maka bukan berarti dia jadi layak dikecewakan, dikhianati, dan diperlakukan tidak adil.",
    "Bagaimanapun keadaan kita, mau sedih, bahagia, waktu tidak pernah berhenti menunggu. Waktu tetap berjalan.",
    "Menangis tidak selalu simbol lemah tak berdaya. Menangis dalam situasi tertentu justru adalah simbol kekuatan, kesabaran, dan kehormatan.",
    "Apa pun yang terlihat, boleh jadi tidak seperti yang kita lihat. Apa pun yang hilang, tidak selalu lenyap seperti yang kita duga.",
    "Hidup ini adalah perjalanan panjang dan tidak selalu mulus. Pada hari ke berapa dan pada jam ke berapa, kita tidak pernah tahu, rasa sakit apa yang harus kita lalui. Kita tidak tahu, kapan hidup akan mebanting kita dalam sekali, membuat terduduk, untuk kemudian memaksa kita mengambil keputusan.",
    "Jika kita tidak mudah menyerah, maka kita sudah dekat sekali dengan kesuksesan.",
    "Di dunia ini, ada dua orang yang susah sekali dikalahkan, yakni orang yang sabar dan orang yang tidak mudah menyerah.",
    "Akan selalu ada hari-hari menyakitkan dan kita tidak tahu kapan hari itu menghantam kita. Tapi akan selalu ada hari-hari berikutnya, memulai bab yang baru bersama matahari terbit.",
    "Hidup ini tidak seperti novel, yang kita bisa mengulang halaman pertama kapan pun kita mau. Dalam kehidupan nyata, saat sebuah kisah tidak lagi asyik, mulai menyakitkan, kita tidak bisa mengulanginya dari halaman pertama lagi. Tapi tidak mengapa, karena kita selalu bisa membuat bab baru, halaman baru.",
    "Inilah hidupku, dan aku tidak peduli apa pun penilaian kalian. Toh, aku hidup bukan untuk membahagiakan orang lain, apalagi menghabiskan waktu mendengar komentar mereka.",
    "Jangan menghukum kesempatan dengan penantian. Karena terkadang melepaskan sesuatu justru memperoleh yang terbaik.",
    "Hidup ini memang tentang menunggu. Menunggu kita untuk menyadari, kapan kita akan berhenti menunggu.",
    "Benarlah kata orang, meski semua hal itu adalah kenangan menyakitkan, kita baru merasa kehilangan setelah sesuatu itu benar-benar pergi, tidak akan mungkin kembali lagi.",
    "Tidak selalu yang kita pikirkan itu benar. Tidak selalu yang kita sangkakan itu kebenaran. Kalau kita tidak mengerti alasan sebenarnya bukan berarti semua jadi buruk dan salah menurut versi kita sendiri.",
    "Saat kita memutuskan memaafkan seseorang, itu bukan persoalan apakah orang itu salah, dan kita benar. Apakah orang itu memang jahat atau aniaya, bukan. Kita memutuskan memaafkan seseorang karena kita berhak atas kedamaian di dalam hati.",
    "Tidak ada kehilangan yang paling menyedihkan di dunia ini selain kehilangan kejujuran, harga diri, dan martabat.",
    "Persahabatan itu tidak terbuat dari sesuatu yang besar. Melainkan, dibangun dari hal-hal kecil yang kemudian saat dikumpulkan ternyata menjadi besar.",
    "Sejatinya, dalam hidup ini kita tidak pernah berusaha mengalahkan orang lain, dan itu sama sekali tidak perlu. Kita cukup mengalahkan diri sendiri.",
    "Seseorang itu mungkin terlihat banyak kekurangan di mata kita, tapi boleh jadi itu pilihan yang baik. Sebaliknya, seseorang itu mungkin terlihat perfect, sempurna di mata kita, tapi boleh jadi itu pilihan yang buruk.",
    "Orang kuat itu bukan berarti dia selalu kuat. Tidak. Melainkan dia tahu sekali kapan harus berjuang habis-habisan, kapan harus siap tulus melepaskan.",
    "Jika kita berdoa, lantas situasi tetap begitu-begitu saja, tidak ada yang berubah, bukan berarti doa kita tidak makbul, boleh jadi, Tuhan sedang menguji agar hati kitalah yang berubah terlebih dulu.",
    "Bung, hidup ini hanya senda gurau. Jangan terlalu seriuslah apalagi ngotot-ngototan. Sesekali mari kita tertawa, mengolok-olok diri sendiri.",
    "Percayalah, sepanjang kita punya mimpi, punya rencana, walaupun kecil tapi masuk akal, tidak boleh sekalipun rasa sedih, rasa tak berguna itu datang mengganggu pikiran.",
    "Kepedulian kita hari ini akan memberikan perbedaan berarti pada masa depan. Kecil saja, sepertinya sepele, tapi bisa besar dampaknya pada masa mendatang.",
    "Kita tidak perlu menjelaskan hal-hal kepada orang yang tidak mau mendengarkan penjelasan. Jangan menghabiskan waktu.",
    "Kawan, jangan habiskan air mata menangisi seseorang yang jangan-jangan tidak pernah menangis untuk kita.",
    "Hidup kita memang tidak sempurna. Tapi kita bisa membuatnya lengkap dengan selalu berterima kasih.",
    "Jika kita tidak pernah bersyukur. Atas hari-hari lapang dan menyenangkan. Maka, apa pantasnya kita mengeluh pada Tuhan saat hidup kita sempit dan menyedihkan?",
    " Hidup ini kadang memang ganjil sekali. Ada miliaran orang, tapi kita menambatkan satu hati. Ada berjuta kesempatan, tapi kita memilih satu saja. Hidup ini memang kadang rumit sekali. Ada banyak hari esok, tapi kita tak beranjak. Terlalu banyak hari kemarin, tapi kita terus terbenam.",
    "Pertanyaan paling penting adalah bukan berapa kali kita gagal, melainkan berapa kali kita bangkit lagi, lagi, dan lagi dan lagi setelah gagal tersebut.",
    "Manusia mungkin saja merasa berkuasa di atas muka bumi, merasa sebagai spesies paling unggul, tapi mereka sebenarnya dalam posisi sangat lemah saat berhadapan dengn kekuatan alam.",
    "Orang-orang kuat itu selalu berbesar hati. Saking besarnya, kesedihan apapun, tetap muat di dalam hatinya, tidak luber, tidak membuatnya rusuh, banyak mengeluh, apalagi sampai merusak dirinya sendiri.",
    "Kejadian besar selalu bisa membuat orang cepat dewasa. Mereka tidak bisa menghindar, tidak bisa melawan. Mereka hanya bisa memeluk semua kesedihan, memeluknya erat-erat.",
    "Kamu tidak membutuhkan kekuatan besar, atau senjata-senjata terbaik untuk menemukan bunga matahari pertama mekar. Kamu cukup memiliki keberanian, kehormatan, ketulusan, dan yang paling penting, mendengarkan alam liar tersebut.",
    "Berasumsi dengan perasaan, sama saja dengan membiarkan hati kau diracuni harapan baik, padahal boleh jadi kenyataannya tidak seperti itu, menyakitkan.",
    "Jika kita berdoa, lantas semuanya terwujud 100%, bukan berarti doa kita manjur, boleh jadi, Tuhan sedang menguji rasa syukur kita. Apakah kita berterima-kasih atau tidak.",
    "Sepanjang kita yakin telah melakukan sesuatu dengan baik, selalu belajar untuk lebih baik, terbuka dengan masukan, rasa nyaman dan tenteram itu akan datang. Kemuliaan hidup tidak pernah tertukar.",
    "Jangan pernah bersedih ketika orang-orang menilai hidup kita rendah. Karena sejatinya kemuliaan tidak pernah tertukar. Boleh jadi orang-orang yang menghina itulah yang lebih hina.",
    "Hidup ini tidak perlu dibuat rumit, kadangkala cukup dibiarkan saja mengalir seperti sungai. Bahkan saat bertemu bendungan yang tinggi sekali, air bisa terus bersabar, bersabar, dan bersabar, hingga terkumpul banyak dan bisa melampaui tinggi bendungan, lantas bisa melanjutkan alirannya.",
    "Segala sesuatu yang baik, selalu datang di saat terbaiknya. Persis waktunya. Tidak datang lebih cepat, pun tidak lebih lambat. Itulah kenapa rasa sabar itu harus disertai keyakinan.",
    "Rasa marah, panik, cemas, bisa diubah menjadi kekuatan besar. Tapi itu bukan sumber motivasi yang baik. Kita tidak berharap kamu terdesak oleh sesuatu baru berhasil mengeluarkan kekuatan itu, bukan?",
    "Apa pun yang hilang, tidak selalu lenyap seperti yang kita duga. Ada banyak sekali jawaban dari tempat-tempat yang hilang. Kamu akan memperoleh semua jawaban. Masa lalu, hari ini, juga masa depan.",
    "Ada banyak masalah di dunia ini yang bisa jadi kita mati-matian menyelesaikannya, susah sekali jalan keluarnya, ternyata cukup diselesaikan dengan ketulusan, dan jalan keluar atas masalah itu hadir seketika.",
    "Penjelasan akan tiba pada waktu yang pas, tempat yang cocok, dan dari orang yang tepat."
];